// Releases data — sample catalog for Roc Universa workspace

const RELEASES = [
  {
    id: 'r1',
    title: 'Over The Fence',
    artist: 'Miranda Lambert',
    artistInitials: 'ML',
    artistColor: '#8C1F13',
    date: 'Jun 5, 2026',
    dateShort: 'Jun 5',
    relative: 'in 48 days',
    owner: 'Sean Carter',
    ownerInitials: 'SC',
    status: 'progress',
    statusLabel: 'In Progress',
    progress: 12,
    tasks: { todo: 34, done: 4, overdue: 0, total: 38 },
    late: [],
    upcoming: [
      { t: 'Master delivery to DSPs', d: 'Apr 22' },
      { t: 'Cover art final review', d: 'Apr 25' },
    ],
    column: 'setup',
  },
  {
    id: 'r2',
    title: 'Petty Thang',
    artist: 'Bryant Barnes',
    artistInitials: 'BB',
    artistColor: '#E83E18',
    date: 'Jun 28, 2026',
    dateShort: 'Jun 28',
    relative: 'in 71 days',
    owner: 'Sean Carter',
    ownerInitials: 'SC',
    status: 'progress',
    statusLabel: 'In Progress',
    progress: 9,
    tasks: { todo: 89, done: 9, overdue: 5, total: 103 },
    late: [
      { t: 'Save Creative Direction for Petty Thang', d: '2d late' },
      { t: 'Finalize Budget Allocation & Campaign Brief', d: '1d late' },
    ],
    upcoming: [
      { t: 'Street Activation Begins — Flyer & Sticker Drop', d: 'Tmrw' },
      { t: 'Peek A Boo I See You — preview edit', d: 'Tmrw' },
    ],
    column: 'rollout',
    pinned: true,
  },
  {
    id: 'r3',
    title: 'My Oh My',
    artist: 'Ava Max',
    artistInitials: 'AM',
    artistColor: '#F4833E',
    date: 'Mar 20, 2026',
    dateShort: 'Mar 20',
    relative: 'released',
    owner: 'Sean Carter',
    ownerInitials: 'SC',
    status: 'released',
    statusLabel: 'Released',
    progress: 100,
    tasks: { todo: 0, done: 62, overdue: 0, total: 62 },
    late: [],
    upcoming: [
      { t: 'Week 4 performance report', d: 'Apr 21' },
    ],
    column: 'released',
  },
  {
    id: 'r4',
    title: "Cory's Song",
    artist: 'Middle Part',
    artistInitials: 'MP',
    artistColor: '#0E0E10',
    date: 'Jun 2, 2026',
    dateShort: 'Jun 2',
    relative: 'in 45 days',
    owner: 'Jake Truman',
    ownerInitials: 'JT',
    status: 'progress',
    statusLabel: 'In Progress',
    progress: 0,
    tasks: { todo: 0, done: 0, overdue: 0, total: 0 },
    late: [],
    upcoming: [
      { t: 'Brief kickoff with A&R', d: 'Apr 22' },
    ],
    column: 'setup',
  },
  {
    id: 'r5',
    title: 'North Loop',
    artist: 'Omar Apollo',
    artistInitials: 'OA',
    artistColor: '#5A1710',
    date: 'May 2, 2026',
    dateShort: 'May 2',
    relative: 'in 14 days',
    owner: 'Sean Carter',
    ownerInitials: 'SC',
    status: 'progress',
    statusLabel: 'In Progress',
    progress: 68,
    tasks: { todo: 14, done: 30, overdue: 1, total: 45 },
    late: [
      { t: 'Spotify Canvas deliverable', d: '1d late' },
    ],
    upcoming: [
      { t: 'Pre-save waterfall → TikTok', d: 'Tmrw' },
      { t: 'Fan-radio NPR pitch', d: 'Apr 24' },
    ],
    column: 'rollout',
  },
  {
    id: 'r6',
    title: 'Blue Hour',
    artist: 'Phoebe Wren',
    artistInitials: 'PW',
    artistColor: '#BF2A14',
    date: 'Jul 12, 2026',
    dateShort: 'Jul 12',
    relative: 'in 85 days',
    owner: 'Nia Bridges',
    ownerInitials: 'NB',
    status: 'scheduled',
    statusLabel: 'Scheduled',
    progress: 22,
    tasks: { todo: 38, done: 11, overdue: 0, total: 49 },
    late: [],
    upcoming: [
      { t: 'Press embargo brief', d: 'May 3' },
    ],
    column: 'setup',
  },
  {
    id: 'r7',
    title: 'Hemlock',
    artist: 'James Spade',
    artistInitials: 'JS',
    artistColor: '#3B0F08',
    date: 'Apr 25, 2026',
    dateShort: 'Apr 25',
    relative: 'in 7 days',
    owner: 'Sean Carter',
    ownerInitials: 'SC',
    status: 'progress',
    statusLabel: 'In Progress',
    progress: 88,
    tasks: { todo: 4, done: 32, overdue: 0, total: 36 },
    late: [],
    upcoming: [
      { t: 'Release-day thread from label', d: 'Apr 25' },
    ],
    column: 'rollout',
  },
  {
    id: 'r8',
    title: 'Featherweight',
    artist: 'Harlo Montez',
    artistInitials: 'HM',
    artistColor: '#F25A22',
    date: 'Feb 8, 2026',
    dateShort: 'Feb 8',
    relative: 'released',
    owner: 'Nia Bridges',
    ownerInitials: 'NB',
    status: 'released',
    statusLabel: 'Released',
    progress: 100,
    tasks: { todo: 0, done: 48, overdue: 0, total: 48 },
    late: [],
    upcoming: [],
    column: 'released',
  },
  {
    id: 'r9',
    title: 'Safe Harbor',
    artist: 'The Longshore',
    artistInitials: 'LS',
    artistColor: '#8A8A94',
    date: 'TBD',
    dateShort: 'TBD',
    relative: 'on hold',
    owner: 'Jake Truman',
    ownerInitials: 'JT',
    status: 'hold',
    statusLabel: 'On Hold',
    progress: 4,
    tasks: { todo: 12, done: 1, overdue: 0, total: 13 },
    late: [],
    upcoming: [],
    column: 'setup',
  },
];

const COLUMNS = [
  { id: 'setup',    name: 'Pre-Production', badge: '#CFCCC1' },
  { id: 'rollout',  name: 'Active Rollout', badge: '#E83E18' },
  { id: 'release',  name: 'Release Week',   badge: '#F4833E' },
  { id: 'released', name: 'Post-Release',   badge: '#A8D84A' },
];

window.RELEASES = RELEASES;
window.COLUMNS  = COLUMNS;
