/**
 * Investor deck server runtime.
 *
 * The deck page and its API routes share this module. It deliberately has no
 * dependencies beyond WebCrypto (available in the Cloudflare Worker and in
 * Node >= 20 for `astro dev`), because it runs inside the Worker bundle.
 *
 * Content model: `compiled.json` (generated by scripts/compile-investor-deck.mjs)
 * holds the deck as parts + per-slot defaults. Stored overrides — a flat map of
 * slot slug -> inline-HTML fragment — are merged at request time, so publishing
 * an edit is a KV write, not a rebuild.
 *
 * Storage: Cloudflare KV binding `INVESTOR_DECK` in production (added in the
 * Pages dashboard — see INVESTOR-DECK.md), a repo-local JSON file during
 * `astro dev`. Absent both, the page renders template defaults and edit mode
 * reports storage as unconfigured — the route never hard-fails.
 */
import compiled from "./compiled.json";

export type OverrideMap = Record<string, string>;
export interface DeckDoc {
  content: OverrideMap;
  updatedAt: string;
  updatedBy: string;
}
export interface GateConfig {
  enabled: boolean;
  salt?: string;
  hash?: string;
  v: number; // bumped on password change to invalidate old gate cookies
}
export interface DeckConfig {
  gate: GateConfig;
}

export const SLOT_SLUGS: Set<string> = new Set(
  Object.keys((compiled as any).defaults)
);

/* ------------------------------------------------------------------ render */

// Inline formatting only. Everything else is dropped; attributes are dropped
// except a conservatively-charset class on <span> (the deck uses styled spans
// like .tbd/.ital). This runs on write AND on render (defense in depth) —
// overrides land in the page as raw HTML, so nothing outside this whitelist
// may survive.
const ALLOWED_TAGS = new Set(["em", "strong", "b", "i", "br", "span", "sup", "sub"]);

export function sanitizeFragment(input: string): string {
  if (typeof input !== "string") return "";
  return input.replace(/<[^>]*>?/g, (tag) => {
    const m = tag.match(/^<\s*(\/?)\s*([a-zA-Z0-9]+)([^>]*)>$/);
    if (!m) return "";
    const close = m[1];
    const name = m[2].toLowerCase();
    const attrs = m[3] || "";
    if (!ALLOWED_TAGS.has(name)) return "";
    if (close) return name === "br" ? "" : `</${name}>`;
    if (name === "br") return "<br>";
    if (name === "span") {
      const cm = attrs.match(/class\s*=\s*"([a-zA-Z0-9 _-]{0,64})"/);
      return cm ? `<span class="${cm[1]}">` : "<span>";
    }
    return `<${name}>`;
  });
}

export const MAX_SLOT_LENGTH = 4000;

export function renderDeck(overrides: OverrideMap | null | undefined): string {
  const o = overrides || {};
  const defaults = (compiled as any).defaults as Record<string, string>;
  let out = "";
  for (const part of (compiled as any).parts as Array<string | { s: string }>) {
    if (typeof part === "string") {
      out += part;
    } else {
      const ov = o[part.s];
      out += typeof ov === "string" ? sanitizeFragment(ov) : defaults[part.s] ?? "";
    }
  }
  return out;
}

/* -------------------------------------------------------------------- env */

export function getEnv(locals: any): Record<string, string | undefined> {
  const runtime = locals?.runtime?.env ?? {};
  return new Proxy(
    {},
    {
      get: (_t, key: string) =>
        runtime[key] ?? (import.meta.env as any)[key],
    }
  ) as Record<string, string | undefined>;
}

export function getSecret(env: Record<string, string | undefined>): string | null {
  const s = env.INVESTOR_SESSION_SECRET;
  if (s && s.length >= 16) return s;
  // Dev-only fallback so the flow is testable without configuration. Never
  // active in a production build.
  if (import.meta.env.DEV) return "dev-only-secret-not-for-production";
  return null;
}

/* ------------------------------------------------------------------ tokens */

const te = new TextEncoder();

function b64url(bytes: ArrayBuffer | Uint8Array): string {
  const b = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  let s = "";
  for (const x of b) s += String.fromCharCode(x);
  return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function b64urlDecodeToString(s: string): string {
  const pad = s.length % 4 === 0 ? "" : "=".repeat(4 - (s.length % 4));
  return atob(s.replace(/-/g, "+").replace(/_/g, "/") + pad);
}

async function hmac(secret: string, data: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    te.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const sig = await crypto.subtle.sign("HMAC", key, te.encode(data));
  return b64url(sig);
}

/** payload must be a plain object; an `x` field (epoch seconds) is enforced on verify. */
export async function signToken(payload: object, secret: string): Promise<string> {
  const body = b64url(te.encode(JSON.stringify(payload)));
  const sig = await hmac(secret, body);
  return `${body}.${sig}`;
}

export async function verifyToken(
  token: string | undefined | null,
  secret: string
): Promise<any | null> {
  if (!token) return null;
  const dot = token.lastIndexOf(".");
  if (dot < 1) return null;
  const body = token.slice(0, dot);
  const sig = token.slice(dot + 1);
  const expect = await hmac(secret, body);
  if (sig.length !== expect.length) return null;
  // constant-time-ish compare
  let diff = 0;
  for (let i = 0; i < sig.length; i++) diff |= sig.charCodeAt(i) ^ expect.charCodeAt(i);
  if (diff !== 0) return null;
  try {
    const payload = JSON.parse(b64urlDecodeToString(body));
    if (typeof payload.x !== "number" || payload.x * 1000 < Date.now()) return null;
    return payload;
  } catch {
    return null;
  }
}

export async function sha256Hex(s: string): Promise<string> {
  const d = await crypto.subtle.digest("SHA-256", te.encode(s));
  return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/* ------------------------------------------------------------------- store */

export interface DeckStore {
  kind: "kv" | "dev";
  get(key: "draft" | "published" | "config"): Promise<any | null>;
  put(key: "draft" | "published" | "config", value: any): Promise<void>;
}

const KV_PREFIX = "investor-deck:";

export function getStore(locals: any): DeckStore | null {
  const kv = locals?.runtime?.env?.INVESTOR_DECK;
  if (kv && typeof kv.get === "function") {
    return {
      kind: "kv",
      async get(key) {
        const raw = await kv.get(KV_PREFIX + key);
        return raw ? JSON.parse(raw) : null;
      },
      async put(key, value) {
        await kv.put(KV_PREFIX + key, JSON.stringify(value));
      },
    };
  }
  if (import.meta.env.DEV) {
    return devFileStore();
  }
  return null;
}

// astro dev runs in Node, so a JSON file beside the repo gives the full
// draft/publish/gate loop locally with zero setup. The indirect import
// keeps node:fs out of the Worker bundle's static graph.
function devFileStore(): DeckStore {
  const FILE = ".investor-deck-dev.json";
  const load = async () => {
    const fs = await import(/* @vite-ignore */ "node:" + "fs");
    try {
      return JSON.parse(fs.readFileSync(FILE, "utf8"));
    } catch {
      return {};
    }
  };
  return {
    kind: "dev",
    async get(key) {
      const all = await load();
      return all[key] ?? null;
    },
    async put(key, value) {
      const fs = await import(/* @vite-ignore */ "node:" + "fs");
      const all = await load();
      all[key] = value;
      fs.writeFileSync(FILE, JSON.stringify(all, null, 2));
    },
  };
}

/* ------------------------------------------------------------------- admin */

const DEFAULT_ALLOWLIST = "@teamrollouts.com,@teamforartists.com";

export function isAllowedEmail(
  email: string,
  env: Record<string, string | undefined>
): boolean {
  const raw = env.INVESTOR_ADMIN_EMAILS || DEFAULT_ALLOWLIST;
  const needle = email.trim().toLowerCase();
  return raw
    .split(",")
    .map((e) => e.trim().toLowerCase())
    .filter(Boolean)
    .some((e) => (e.startsWith("@") ? needle.endsWith(e) : needle === e));
}

export const ADMIN_COOKIE = "inv_admin";
export const GATE_COOKIE = "inv_gate";

/** Returns the admin email, or null. Honors the dev bypass under `astro dev` only. */
export async function getAdminEmail(
  cookies: { get(name: string): { value: string } | undefined },
  env: Record<string, string | undefined>
): Promise<string | null> {
  if (import.meta.env.DEV && env.INVESTOR_DEV_ADMIN === "1") return "dev@localhost";
  const secret = getSecret(env);
  if (!secret) return null;
  const payload = await verifyToken(cookies.get(ADMIN_COOKIE)?.value, secret);
  if (!payload || typeof payload.e !== "string") return null;
  if (!isAllowedEmail(payload.e, env)) return null;
  return payload.e;
}

export async function hasGateAccess(
  cookies: { get(name: string): { value: string } | undefined },
  env: Record<string, string | undefined>,
  gate: GateConfig
): Promise<boolean> {
  if (!gate.enabled) return true;
  const secret = getSecret(env);
  if (!secret) return false;
  const payload = await verifyToken(cookies.get(GATE_COOKIE)?.value, secret);
  return !!payload && payload.v === gate.v;
}

export function defaultConfig(): DeckConfig {
  return { gate: { enabled: false, v: 1 } };
}

/* --------------------------------------------------------------- responses */

export function noStoreHeaders(extra: Record<string, string> = {}): Headers {
  return new Headers({
    "Cache-Control": "private, no-store",
    "X-Robots-Tag": "noindex, nofollow",
    ...extra,
  });
}

export function json(data: unknown, status = 200, extra: Record<string, string> = {}): Response {
  const h = noStoreHeaders({ "Content-Type": "application/json", ...extra });
  return new Response(JSON.stringify(data), { status, headers: h });
}

/** Cross-origin mutation guard for the API routes. */
export function sameOriginOk(request: Request, url: URL): boolean {
  const origin = request.headers.get("origin");
  if (!origin) return true; // non-browser client or same-origin GET
  return origin === url.origin;
}

export function cookieHeader(
  name: string,
  value: string,
  maxAgeSeconds: number
): string {
  return [
    `${name}=${value}`,
    "Path=/",
    `Max-Age=${maxAgeSeconds}`,
    "HttpOnly",
    "Secure",
    "SameSite=Lax",
  ].join("; ");
}
